module.exports = {
  apps: [
    {
      name: 'clow',
      script: 'dist/server/server.js',
      cwd: '/opt/system-clow',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      node_args: ['--max-old-space-size=1024'],
      env: {
        NODE_ENV: 'production',
      },
      time: true,
      out_file: '/root/.pm2/logs/clow-out.log',
      error_file: '/root/.pm2/logs/clow-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      kill_timeout: 5000,
      listen_timeout: 8000,
      exp_backoff_restart_delay: 200,
    },
    {
      name: 'litellm',
      script: '/opt/litellm/start.sh',
      cwd: '/opt/litellm',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      time: true,
      out_file: '/root/.pm2/logs/litellm-out.log',
      error_file: '/root/.pm2/logs/litellm-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
