/**
 * PluginManifest.ts — Plugin manifest helpers: read, write, extract fields
 *
 * Based on Claude Code's pluginManifest.ts (~250 lines)
 *
 * Features:
 *   - Read manifest from plugin directory
 *   - Write manifest (for plugin creation/update)
 *   - Path resolution
 *   - Component counting
 *   - Permission extraction
 *   - Manifest merging (for config overrides)
 *   - Manifest diffing (for update detection)
 *   - Size validation
 *   - Manifest validation with detailed error messages
 *   - Manifest migration (v1 -> v2)
 *   - Manifest template generation
 *   - Manifest comparison for changelogs
 *   - Manifest size analysis
 */

import * as fs from 'fs';
import * as fsp from 'fs/promises';
import * as path from 'path';
import { PLUGIN_MANIFEST_DIR, PLUGIN_MANIFEST_FILE } from './types.js';
import type { PluginManifest, PluginPermission, PluginCategory } from './types.js';
import { validatePluginManifest } from './PluginManifestSchema.js';

// ─── Constants ──────────────────────────────────────────────────────────────

const MAX_MANIFEST_SIZE = 1024 * 1024; // 1MB

// ─── Types ──────────────────────────────────────────────────────────────────

/** Detailed validation result including field-level context. */
interface DetailedValidationResult {
  valid: boolean;
  errors: Array<{ field: string; message: string; suggestion?: string }>;
  warnings: Array<{ field: string; message: string }>;
}

/** A single entry in a changelog generated by manifest comparison. */
interface ChangelogEntry {
  field: string;
  type: 'added' | 'removed' | 'changed';
  oldValue?: string;
  newValue?: string;
  description: string;
}

/** Size analysis breakdown for a manifest. */
interface ManifestSizeAnalysis {
  totalBytes: number;
  fieldSizes: Record<string, number>;
  largestField: string;
  warningFields: string[];
}

// ─── Read and Validation Operations ────────────────────────────────────────

/**
 * Read and validate a plugin manifest from disk.
 * Returns null if file doesn't exist or is invalid.
 */
export async function readManifest(pluginDir: string): Promise<PluginManifest | null> {
  const fp = manifestPath(pluginDir);
  if (!fs.existsSync(fp)) return null;

  try {
    // Size check
    const stat = await fsp.stat(fp);
    if (stat.size > MAX_MANIFEST_SIZE) {
      console.warn(`[PluginManifest] Manifest too large: ${stat.size} bytes (max ${MAX_MANIFEST_SIZE})`);
      return null;
    }

    const content = await fsp.readFile(fp, 'utf-8');
    const raw = JSON.parse(content);
    const result = validatePluginManifest(raw);

    if (result.valid) return result.data;

    console.warn(`[PluginManifest] Validation failed for ${fp}:`, result.errors.map(e => e.message).join(', '));
    return null;
  } catch (err) {
    console.warn(`[PluginManifest] Failed to read ${fp}: ${(err as Error).message}`);
    return null;
  }
}

/**
 * Read manifest without validation (raw JSON).
 */
export async function readManifestRaw(pluginDir: string): Promise<Record<string, unknown> | null> {
  const fp = manifestPath(pluginDir);
  if (!fs.existsSync(fp)) return null;

  try {
    return JSON.parse(await fsp.readFile(fp, 'utf-8'));
  } catch {
    return null;
  }
}

// ─── Write Operations ───────────────────────────────────────────────────────

/**
 * Write a manifest to disk.
 */
export async function writeManifest(pluginDir: string, manifest: PluginManifest): Promise<void> {
  const dir = path.join(pluginDir, PLUGIN_MANIFEST_DIR);
  await fsp.mkdir(dir, { recursive: true });
  const fp = path.join(dir, PLUGIN_MANIFEST_FILE);
  await fsp.writeFile(fp, JSON.stringify(manifest, null, 2));
}

// ─── Path Helpers ───────────────────────────────────────────────────────────

/**
 * Get the manifest file path for a plugin directory.
 */
export function manifestPath(pluginDir: string): string {
  return path.join(pluginDir, PLUGIN_MANIFEST_DIR, PLUGIN_MANIFEST_FILE);
}

/**
 * Check if a plugin directory has a manifest.
 */
export function hasManifest(pluginDir: string): boolean {
  return fs.existsSync(manifestPath(pluginDir));
}

// ─── Component Analysis ─────────────────────────────────────────────────────

/**
 * Count total components declared in manifest.
 */
export function getComponentCount(m: PluginManifest): number {
  let n = 0;
  if (m.commands?.length) n += m.commands.length;
  if (m.agents?.length) n += m.agents.length;
  if (m.skills?.length) n += m.skills.length;
  if (m.hooks) n++;
  if (m.mcpServers) n += Object.keys(m.mcpServers).length;
  if (m.tools?.length) n += m.tools.length;
  if (m.outputStyles?.length) n += m.outputStyles.length;
  return n;
}

/**
 * Get list of required permissions.
 */
export function getRequiredPermissions(m: PluginManifest): PluginPermission[] {
  return m.requiredPermissions ?? [];
}

/**
 * Get dependency count.
 */
export function getDependencyCount(m: PluginManifest): number {
  return Object.keys(m.dependencies ?? {}).length + Object.keys(m.peerDependencies ?? {}).length;
}

/**
 * Check if manifest has any dangerous permissions.
 */
export function hasDangerousPermissions(m: PluginManifest): boolean {
  const dangerous: PluginPermission[] = ['shell-execution', 'modify-permissions', 'access-secrets'];
  return (m.requiredPermissions ?? []).some(p => dangerous.includes(p));
}

// ─── Manifest Merging ───────────────────────────────────────────────────────

/**
 * Merge user config overrides into a manifest.
 * Only merges safe fields (config, defaultConfig).
 */
export function mergeConfig(
  manifest: PluginManifest,
  overrides: Record<string, unknown>,
): PluginManifest {
  return {
    ...manifest,
    defaultConfig: {
      ...(manifest.defaultConfig ?? {}),
      ...overrides,
    },
  };
}

// ─── Manifest Diffing ───────────────────────────────────────────────────────

/**
 * Compare two manifests and return changed fields.
 */
export function diffManifests(
  a: PluginManifest,
  b: PluginManifest,
): string[] {
  const changed: string[] = [];
  const allKeys = new Set([...Object.keys(a), ...Object.keys(b)]);

  for (const key of allKeys) {
    const va = JSON.stringify((a as unknown as Record<string, unknown>)[key]);
    const vb = JSON.stringify((b as unknown as Record<string, unknown>)[key]);
    if (va !== vb) changed.push(key);
  }

  return changed;
}

/**
 * Check if the version changed between two manifests.
 */
export function versionChanged(a: PluginManifest, b: PluginManifest): boolean {
  return a.version !== b.version;
}

/**
 * Create a summary string for a manifest.
 */
export function manifestSummary(m: PluginManifest): string {
  const parts = [`${m.name}@${m.version}`];
  const components = getComponentCount(m);
  if (components > 0) parts.push(`${components} components`);
  const deps = getDependencyCount(m);
  if (deps > 0) parts.push(`${deps} deps`);
  if (m.category) parts.push(m.category);
  return parts.join(' | ');
}

// ─── Detailed Validation ────────────────────────────────────────────────────

/**
 * Validate a manifest and return detailed, field-level error messages
 * together with actionable suggestions.
 */
export function validateManifestDetailed(raw: unknown): DetailedValidationResult {
  const errors: DetailedValidationResult['errors'] = [];
  const warnings: DetailedValidationResult['warnings'] = [];

  if (!raw || typeof raw !== 'object') {
    errors.push({ field: '(root)', message: 'Manifest must be a JSON object', suggestion: 'Ensure the file contains a valid JSON object.' });
    return { valid: false, errors, warnings };
  }

  const obj = raw as Record<string, unknown>;

  // Name
  if (!obj.name) {
    errors.push({ field: 'name', message: 'Name is required', suggestion: 'Add a "name" field with a kebab-case identifier.' });
  } else if (typeof obj.name !== 'string') {
    errors.push({ field: 'name', message: 'Name must be a string' });
  } else if (!/^[a-z0-9][a-z0-9-]*$/.test(obj.name)) {
    errors.push({ field: 'name', message: 'Name must be kebab-case', suggestion: `Try "${String(obj.name).toLowerCase().replace(/[^a-z0-9-]/g, '-')}"` });
  }

  // Version
  if (!obj.version) {
    errors.push({ field: 'version', message: 'Version is required', suggestion: 'Use semver, e.g. "1.0.0"' });
  } else if (typeof obj.version !== 'string' || !/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(obj.version)) {
    errors.push({ field: 'version', message: 'Version must be valid semver', suggestion: 'Use format X.Y.Z, e.g. "1.0.0"' });
  }

  // Description
  if (!obj.description) {
    errors.push({ field: 'description', message: 'Description is required', suggestion: 'Provide a short (10-500 chars) description.' });
  } else if (typeof obj.description === 'string' && obj.description.length < 10) {
    errors.push({ field: 'description', message: 'Description must be at least 10 characters' });
  }

  // Optional warnings
  if (!obj.author) {
    warnings.push({ field: 'author', message: 'Consider adding an author field' });
  }
  if (!obj.license) {
    warnings.push({ field: 'license', message: 'Consider specifying a license' });
  }
  if (!obj.repository) {
    warnings.push({ field: 'repository', message: 'Consider adding a repository URL' });
  }

  return { valid: errors.length === 0, errors, warnings };
}

// ─── Manifest Migration (v1 -> v2) ─────────────────────────────────────────

/**
 * Migrate a v1-style manifest to v2.
 *
 * V1 manifests used flat string arrays for MCP servers and lacked
 * the `config` / `defaultConfig` separation.  This function
 * normalises them to the current schema.
 */
export function migrateManifestV1ToV2(v1: Record<string, unknown>): Record<string, unknown> {
  const v2: Record<string, unknown> = { ...v1 };

  // Ensure schema version marker
  v2.schemaVersion = 2;

  // Migrate flat mcp strings to objects
  if (Array.isArray(v1.mcpServers)) {
    const servers: Record<string, { command: string }> = {};
    for (const entry of v1.mcpServers as string[]) {
      const name = entry.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
      servers[name] = { command: entry };
    }
    v2.mcpServers = servers;
  }

  // Merge legacy "options" into defaultConfig
  if (v1.options && typeof v1.options === 'object' && !v1.defaultConfig) {
    v2.defaultConfig = v1.options;
    delete v2.options;
  }

  // Rename legacy "tags" field that was an object in v1
  if (v1.tags && typeof v1.tags === 'object' && !Array.isArray(v1.tags)) {
    v2.tags = Object.keys(v1.tags as Record<string, unknown>);
  }

  return v2;
}

// ─── Manifest Template Generation ───────────────────────────────────────────

/**
 * Generate a minimal but valid manifest template.
 * Useful for scaffolding a new plugin.
 */
export function generateManifestTemplate(
  name: string,
  options: {
    description?: string;
    author?: string;
    category?: PluginCategory;
    permissions?: PluginPermission[];
    withMcp?: boolean;
    withHooks?: boolean;
  } = {},
): PluginManifest {
  const manifest: PluginManifest = {
    name,
    version: '0.1.0',
    description: options.description ?? `${name} plugin for Clow`,
  };

  if (options.author) {
    manifest.author = { name: options.author };
  }

  if (options.category) {
    manifest.category = options.category;
  }

  if (options.permissions && options.permissions.length > 0) {
    manifest.requiredPermissions = options.permissions;
  }

  if (options.withMcp) {
    manifest.mcpServers = {
      [`${name}-server`]: {
        command: 'node',
        args: ['dist/server.js'],
        description: `MCP server for ${name}`,
      },
    };
  }

  if (options.withHooks) {
    manifest.hooks = 'hooks.json';
    if (!manifest.requiredPermissions) manifest.requiredPermissions = [];
    if (!manifest.requiredPermissions.includes('register-hooks')) {
      manifest.requiredPermissions.push('register-hooks');
    }
  }

  return manifest;
}

// ─── Manifest Comparison for Changelogs ─────────────────────────────────────

/**
 * Compare two manifests and produce a structured changelog describing
 * every addition, removal, and change.
 */
export function generateChangelog(
  prev: PluginManifest,
  next: PluginManifest,
): ChangelogEntry[] {
  const entries: ChangelogEntry[] = [];
  const prevObj = prev as unknown as Record<string, unknown>;
  const nextObj = next as unknown as Record<string, unknown>;
  const allKeys = new Set([...Object.keys(prevObj), ...Object.keys(nextObj)]);

  for (const key of allKeys) {
    const oldVal = prevObj[key];
    const newVal = nextObj[key];
    const oldJson = JSON.stringify(oldVal);
    const newJson = JSON.stringify(newVal);

    if (oldJson === newJson) continue;

    if (oldVal === undefined) {
      entries.push({ field: key, type: 'added', newValue: newJson, description: `Added ${key}` });
    } else if (newVal === undefined) {
      entries.push({ field: key, type: 'removed', oldValue: oldJson, description: `Removed ${key}` });
    } else {
      entries.push({ field: key, type: 'changed', oldValue: oldJson, newValue: newJson, description: `Changed ${key}` });
    }
  }

  return entries;
}

// ─── Manifest Size Analysis ─────────────────────────────────────────────────

/**
 * Analyse how much space each field occupies in the serialised manifest.
 * Returns a breakdown and flags any fields that are unusually large.
 */
export function analyzeManifestSize(manifest: PluginManifest): ManifestSizeAnalysis {
  const obj = manifest as unknown as Record<string, unknown>;
  const fieldSizes: Record<string, number> = {};
  let largestField = '';
  let largestSize = 0;
  const warningFields: string[] = [];
  const WARNING_THRESHOLD = 10_000; // bytes

  for (const [key, value] of Object.entries(obj)) {
    const size = Buffer.byteLength(JSON.stringify(value) ?? '', 'utf-8');
    fieldSizes[key] = size;
    if (size > largestSize) {
      largestSize = size;
      largestField = key;
    }
    if (size > WARNING_THRESHOLD) {
      warningFields.push(key);
    }
  }

  const totalBytes = Buffer.byteLength(JSON.stringify(manifest), 'utf-8');

  return { totalBytes, fieldSizes, largestField, warningFields };
}
